name: Test

on:
  push:
    branches: [ feature/githubrunner ]

jobs:

  test:

    runs-on:

      - runner-test-noexiste

    steps:

      - run: |
          echo "Hello ARC"
          whoami
          sleep 6000
